### ISSUE TITLE
Question about Step1 and Step2 being separated steps. 

### ISSUE THREAD

**Issue by xinyazha92** [magpie-align/magpie#1]
Hi thank you for this interesting work!
The paper mentions that MAGPIE is a 2-stage pipeline (step1 is instruction generation and step2 is response generation). How is it different to the strategy where Step1 and 2 are unified in one pass? Since LLM is auto regressive, wouldn't the model generate instruction and response altogether?

**Comment by yuchenlin** [comment]
Hey Xinya, thanks for the question! yeah, you're right, technically you generate query 1, response 1, query 2, response 2 all in the same inference (by setting specific stopping criteria).  We choose to use multiple stages to collect them step by step so that we can have more control:
1. we'll need to remove some duplicate queries and queries that are noisy/too easy (see our paper for details). Noisy queries may not end properly with the correct <|eot_id|> so we need to post-process them.
2. we'll need to adjust temperature for sampling query/responses. we find using a high temp for sampling queries is better and lower temp for sampling responses. 
3. also we use API-like inference engine for some inference which would be more efficient for us to monitor the progress by splitting the data collection stages.

**Comment by xinyazha92** [comment]
That makes sense. Thank you for such a quick reply!
