### ISSUE TITLE
How to guide the LLM to generate a specific instruction-response pair?

### ISSUE THREAD

**Issue by AliButtar** [magpie-align/magpie#5]
All the examples right now seem to be random where based on pre-query, you get a random text instruction to which the LLM generates a response. How can I guide it to generate a specific text instruction and response to role play as for example a 24 year old western woman. 

An instruction could be: How do you like the new shoes that were released for Nike for running in winter?
And to the above instruction, the response comes as someone who is 24 years old wester woman who has usually used shoes from adidas only. 

I would like to guide the LLM in both cases and no be completely random. 

Thanks

**Comment by fly-dust** [comment]
Hi,
Thank you for your message. Magpie is designed to generate a general alignment dataset with diverse topic coverage. By design, it is challenging for Magpie to control specific tasks like what you mentioned in the example. We believe it is a promising future research direction!

Meanwhile, I would recommend using other frameworks which support seed instructions. For example, the most classic one is [Self-Instruct](https://github.com/yizhongw/self-instruct). You may also try the latest [GenQA framework](https://arxiv.org/abs/2406.10323). Hope that helps! 😀
