### ISSUE TITLE
Use online LLM inference

### ISSUE THREAD

**Issue by mkaratayev** [magpie-align/magpie#8]
Hi,

Thank you for the excellent project! I have a question: is it possible to use the online inference model with your pipeline?

Thanks in advance!

**Comment by fly-dust** [comment]
Hi,

Since the online inference service provider will automatically provide the template for inference, it cannot be used for generating the instruction (step 1). However, you can use the online inference platform to generate the response (step 2)! You can do this by setting `api=True` and providing a Together api key in [`gen_res.py`](https://github.com/magpie-align/magpie/blob/main/exp/gen_res.py).
