### ISSUE TITLE
Gemma OOM 

### ISSUE THREAD

**Issue by choco9966** [magpie-align/magpie#9]
Hello,

I'm encountering an Out Of Memory (OOM) error while trying to proceed with Gemma using the parameters below. I'm working in an environment with 8 A100 GPUs (80GB each).

```bash
model_path=${1:-"google/gemma-2-9b-it"}
total_prompts=${2:-1000}
ins_topp=${3:-1}
ins_temp=${4:-1}
res_topp=${5:-1}
res_temp=${6:-0}
res_rep=1
device="0,1,2,3,4,5,6,7"
tensor_parallel=8
gpu_memory_utilization=0.95
n=200
batch_size=200
```

Thank you.

**Comment by fly-dust** [comment]
Hi,
Thanks for the message. To run Gemma-2, you need to first upgrade to the latest vllm. Since vllm does not have the official release for Gemma-2, you may need to [build vllm from source](https://docs.vllm.ai/en/latest/getting_started/installation.html#build-from-source).

If, unfortunately, after installing the latest vllm, it is still not working, you may need to decrease the `gpu_memory_utilization`. For example, you can try `gpu_memory_utilization=0.8`.

Also, can you please check if your GPUs are not running other scripts?

Please let me know whether this helps! 🥲

**Comment by fly-dust** [comment]
I also tried Gemma 2 using `vllm==0.5.1`. The results are different from those generated using HF transformers. Maybe we need to wait for a stable vllm version.

**Comment by choco9966** [comment]
Thank you for your response. I was using vllm 0.5.1 and encountered a bug with gpu_memory_utilization=0.95 and a tensor size of 8. I also thought it was a Vllm bug and have been waiting, but some people seem to be inferring with gemma-2-it already, so I'm really not sure.

**Comment by fly-dust** [comment]
Yes... I think so. I will also try from my side. If they fix that, I will ping this issue.

**Comment by fly-dust** [comment]
Hi,
Since the vllm engine is still problematic, I added the HF engine for the Gemma2 series. I also added a series of rules to sanitize instructions for Gemma2. However, since it is HF, the speed would be much slower than vllm...

If you encounter any issues using new scripts, please let me know~

**Comment by choco9966** [comment]
Oh, thank you! I will try it right away.

**Comment by fly-dust** [comment]
Hi! We extracted a bit from Gemma 2 27B [here](https://huggingface.co/datasets/Magpie-Align/Magpie-Gemma2-Pro-Preview). The sanitized version is [here](https://huggingface.co/datasets/Magpie-Align/Magpie-Gemma2-Pro-Preview-Filtered). We are now scaling it up!
